name: Calculate reading time for stories

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  update-times:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Checkout source repo files
        uses: actions/checkout@v4
        with:
          repository: Kengxxiao/ArknightsGameData_YoStar
          path: temp
          ref: main

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: corepack enable && corepack prepare yarn@1 --activate && yarn install --immutable

      - name: Run script to generate JSON
        run: node scripts/reading-time.js temp/en_US/gamedata/story

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Generate Reading Times
          file_pattern: data/reading-time.json
